const KEY="swim-monitor-v1";
const defaults={athletes:[],sessions:[],monitoring:[],zones:["Z1","Z2","Z3","Z4","Z5"],materials:["Palas","Pull buoy","Barbatanas","Elástico","Snorkel","Placa","Outro"]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||defaults;
let view="dashboard";
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random()}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2500)}
function fmt(n){return Number(n||0).toLocaleString("pt-PT")}
function nav(){document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#pageTitle").textContent={dashboard:"Dashboard da equipa",athletes:"Atletas",sessions:"Registo de treinos",monitoring:"Monitorização",settings:"Configurações"}[view];render()}
$("#nav").addEventListener("click",e=>{let b=e.target.closest("button[data-view]");if(b){view=b.dataset.view;nav()}});
$("#quickAdd").onclick=()=>openForm(view==="athletes"?"athlete":view==="monitoring"?"monitor":"session");
$("#exportAll").onclick=()=>exportCSV("todos",Object.entries(db).flatMap(([type,rows])=>Array.isArray(rows)?rows.map(r=>({...r,tipo:type})):[]));
$("#resetDemo").onclick=()=>{if(confirm("Repor os dados demo? Os dados atuais serão substituídos.")){db={...defaults,athletes:[{id:id(),name:"Atleta Demo",team:"Cadetes B2",sex:"F"}],sessions:[],monitoring:[]};save();nav();toast("Dados demo repostos")}};
$("#closeModal").onclick=closeModal;
$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
function openModal(title,html){$("#modalTitle").textContent=title;$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function formShell(fields,submit){return `<form id="recordForm"><div class="form-grid">${fields}</div><div class="actions"><button type="button" class="secondary" id="cancel">Cancelar</button><button class="primary">${submit||"Guardar"}</button></div></form>`}
function field(label,name,value="",type="text",extra=""){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function select(label,name,options,value=""){return `<label>${label}<select name="${name}"><option value="">Selecionar...</option>${options.map(o=>`<option ${o===value?"selected":""} value="${esc(o)}">${esc(o)}</option>`).join("")}</select></label>`}
function bindForm(fn){$("#cancel").onclick=closeModal;$("#recordForm").onsubmit=e=>{e.preventDefault();fn(Object.fromEntries(new FormData(e.target)));closeModal();save();render();toast("Registo guardado")}}
function remove(type,recordId){if(confirm("Tens a certeza que queres eliminar este registo? Esta ação não pode ser desfeita.")){db[type]=db[type].filter(x=>x.id!==recordId);save();render();toast("Registo eliminado")}}
function edit(type,recordId){let r=db[type].find(x=>x.id===recordId);openForm(type==="athletes"?"athlete":type==="monitoring"?"monitor":"session",r)}
function openForm(type,r={}) {
 if(type==="athlete"){openModal(r.id?"Editar atleta":"Novo atleta",formShell(field("Nome completo","name",r.name,"text","required")+field("Equipa / escalão","team",r.team)+select("Sexo","sex",["F","M","Outro"],r.sex)+field("Data de nascimento","birth",r.birth,"date")+field("Data de entrada","joined",r.joined,"date")+`<label class="wide">Observações<textarea name="notes">${esc(r.notes)}</textarea></label>`));bindForm(v=>{if(r.id)Object.assign(r,v);else db.athletes.push({id:id(),active:true,...v})})}
 if(type==="session"){let athleteOpts=db.athletes.filter(a=>a.active!==false).map(a=>`<label><input type="checkbox" name="athletes" value="${a.id}" ${(r.athletes||[]).includes(a.id)?"checked":""}> ${esc(a.name)}</label>`).join("");
 let tasks=r.tasks||[{distance:"",reps:1,style:"Crawl",zone:"Z1",work:"Nado completo",material:"",description:"",interval:"",notes:""}];
 openModal(r.id?"Editar treino":"Novo treino",formShell(field("Data","date",r.date,"date","required")+field("Microciclo","microcycle",r.microcycle,"number","required")+select("Período","period",["AM","PM"],r.period)+field("Tipo de sessão","sessionType",r.sessionType)+`<label class="wide">Atletas presentes<div class="form-grid">${athleteOpts||"<span class='muted'>Cria primeiro os atletas.</span>"}</div></label><div class="wide"><h4>Tarefas</h4><div id="tasks">${tasks.map((t,i)=>taskHTML(t,i)).join("")}</div><button type="button" class="secondary" id="addTask">＋ Adicionar tarefa</button></div>`,"Guardar treino"));
 $("#addTask").onclick=()=>{$("#tasks").insertAdjacentHTML("beforeend",taskHTML({},document.querySelectorAll(".task").length))};
 bindForm(v=>{v.athletes=[...$("#recordForm").querySelectorAll('input[name="athletes"]:checked')].map(x=>x.value);v.tasks=[...$("#tasks").querySelectorAll(".task")].map(el=>Object.fromEntries(new FormData(el)));v.tasks.forEach(t=>{t.distance=Number(t.distance||0);t.reps=Number(t.reps||0);t.total=t.distance*t.reps});if(r.id)Object.assign(r,v);else db.sessions.push({id:id(),...v})});
 }
 if(type==="monitor"){openModal(r.id?"Editar monitorização":"Novo registo de monitorização",formShell(select("Atleta","athleteId",db.athletes.map(a=>a.name),db.athletes.find(a=>a.id===r.athleteId)?.name)+field("Data","date",r.date,"date","required")+field("Microciclo","microcycle",r.microcycle,"number")+select("Período","period",["AM","PM"],r.period)+field("PSE (1-10)","pse",r.pse,"number","min=1 max=10 step=1")+field("FC ao acordar","restHR",r.restHR,"number")+field("Qualidade do sono (1-10)","sleep",r.sleep,"number","min=1 max=10")+field("TRIMP","trimp",r.trimp,"number")+`<label class="wide">Observação<textarea name="notes">${esc(r.notes)}</textarea></label>`));bindForm(v=>{v.athleteId=db.athletes.find(a=>a.name===v.athleteId)?.id||v.athleteId;if(r.id)Object.assign(r,v);else db.monitoring.push({id:id(),...v})})}
}
function taskHTML(t={},i){return `<fieldset class="task"><legend>Tarefa ${i+1}</legend><div class="form-grid">${field("Distância (m)","distance",t.distance,"number","min=0")+field("Repetições","reps",t.reps||1,"number","min=1")+select("Estilo","style",["Crawl","Costas","Bruços","Mariposa","Estilos","Outro"],t.style)+select("Zona","zone",db.zones,t.zone)+select("Tipo de trabalho","work",["Nado completo","Braços","Pernas","Subaquático","Técnica","Outro"],t.work)+select("Material","material",["",...db.materials],t.material)+field("Intervalo / tempo","interval",t.interval)+field("Descrição","description",t.description)+field("Observações","notes",t.notes)}</div></fieldset>`}
function render(){navTitle();({dashboard:renderDashboard,athletes:renderAthletes,sessions:renderSessions,monitoring:renderMonitoring,settings:renderSettings}[view])()}
function navTitle(){}
function renderDashboard(){let meters=db.sessions.reduce((s,x)=>s+(x.tasks||[]).reduce((a,t)=>a+Number(t.total||t.distance*t.reps||0),0),0),pse=db.monitoring.filter(x=>x.pse).map(x=>+x.pse);$("#content").innerHTML=`<div class="grid stats"><div class="card stat"><small>Volume total registado</small><strong>${fmt(meters)} m</strong></div><div class="card stat"><small>Atletas</small><strong>${db.athletes.filter(a=>a.active!==false).length}</strong></div><div class="card stat"><small>Sessões</small><strong>${db.sessions.length}</strong></div><div class="card stat"><small>PSE média</small><strong>${pse.length?(pse.reduce((a,b)=>a+b,0)/pse.length).toFixed(1):"—"}</strong></div></div><div class="section-title"><h3>Volume por zona</h3></div><div class="card">${db.zones.map(z=>{let n=db.sessions.reduce((s,x)=>s+(x.tasks||[]).filter(t=>t.zone===z).reduce((a,t)=>a+Number(t.total||0),0),0);return `<div class="chart-row"><span class="name">${esc(z)}</span><div class="bar"><span style="width:${meters?Math.min(100,n/meters*100):0}%"></span></div><span class="value">${fmt(n)} m</span></div>`}).join("")||"<div class='empty'>Ainda não existem dados.</div>"}</div><div class="section-title"><h3>Últimos treinos</h3><button class="secondary" onclick="view='sessions';nav()">Ver todos</button></div>${sessionTable(db.sessions.slice(-5).reverse())}`}
function renderAthletes(){$("#content").innerHTML=`<div class="section-title"><h3>Lista de atletas</h3><button class="primary" onclick="openForm('athlete')">＋ Adicionar atleta</button></div><div class="card table-wrap">${db.athletes.length?`<table class="table"><thead><tr><th>Nome</th><th>Equipa</th><th>Sexo</th><th>Estado</th><th>Ações</th></tr></thead><tbody>${db.athletes.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.team)}</td><td>${esc(a.sex)}</td><td><span class="tag">${a.active===false?"Inativo":"Ativo"}</span></td><td class="actions-cell"><button class="small edit" onclick="edit('athletes','${a.id}')">Editar</button> <button class="small secondary" onclick="toggleAthlete('${a.id}')">${a.active===false?"Ativar":"Desativar"}</button> <button class="small delete" onclick="remove('athletes','${a.id}')">Eliminar</button></td></tr>`).join("")}</tbody></table>`:"<div class='empty'>Ainda não existem atletas.</div>"}</div>`}
function toggleAthlete(i){let a=db.athletes.find(x=>x.id===i);a.active=a.active===false;save();render()}
function sessionTable(rows){return `<div class="card table-wrap">${rows.length?`<table class="table"><thead><tr><th>Data</th><th>Microciclo</th><th>Período</th><th>Volume</th><th>Atletas</th><th>Ações</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.date)}</td><td>${esc(s.microcycle)}</td><td>${esc(s.period)}</td><td>${fmt((s.tasks||[]).reduce((a,t)=>a+Number(t.total||0),0))} m</td><td>${(s.athletes||[]).length}</td><td><button class="small edit" onclick="edit('sessions','${s.id}')">Editar</button> <button class="small delete" onclick="remove('sessions','${s.id}')">Eliminar</button></td></tr>`).join("")}</tbody></table>`:"<div class='empty'>Ainda não existem treinos.</div>"}</div>`}
function renderSessions(){$("#content").innerHTML=`<div class="section-title"><h3>Sessões realizadas</h3><button class="primary" onclick="openForm('session')">＋ Novo treino</button></div>${sessionTable([...db.sessions].reverse())}`}
function renderMonitoring(){$("#content").innerHTML=`<div class="section-title"><h3>PSE, FC, sono e TRIMP</h3><button class="primary" onclick="openForm('monitor')">＋ Novo registo</button></div><div class="card table-wrap">${db.monitoring.length?`<table class="table"><thead><tr><th>Data</th><th>Atleta</th><th>PSE</th><th>FC acordar</th><th>Sono</th><th>TRIMP</th><th>Ações</th></tr></thead><tbody>${[...db.monitoring].reverse().map(m=>`<tr><td>${esc(m.date)}</td><td>${esc(db.athletes.find(a=>a.id===m.athleteId)?.name||"—")}</td><td>${esc(m.pse)}</td><td>${esc(m.restHR)}</td><td>${esc(m.sleep)}</td><td>${esc(m.trimp)}</td><td><button class="small edit" onclick="edit('monitoring','${m.id}')">Editar</button> <button class="small delete" onclick="remove('monitoring','${m.id}')">Eliminar</button></td></tr>`).join("")}</tbody></table>`:"<div class='empty'>Ainda não existem registos de monitorização.</div>"}</div>`}
function renderSettings(){$("#content").innerHTML=`<div class="grid two"><div class="card"><h3>Zonas de intensidade</h3><p class="muted">Adiciona ou remove as zonas utilizadas pela equipa.</p><form id="zoneForm" class="filters"><input name="zone" placeholder="Nova zona" required><button class="primary">Adicionar</button></form><p>${db.zones.map(z=>`<span class="tag">${esc(z)} <button class="small delete" onclick="removeZone('${esc(z)}')">✕</button></span>`).join(" ")}</p></div><div class="card"><h3>Materiais</h3><p class="muted">Materiais disponíveis nas tarefas.</p><form id="materialForm" class="filters"><input name="material" placeholder="Novo material" required><button class="primary">Adicionar</button></form><p>${db.materials.map(m=>`<span class="tag">${esc(m)} <button class="small delete" onclick="removeMaterial('${esc(m)}')">✕</button></span>`).join(" ")}</p></div></div><div class="card" style="margin-top:16px"><h3>Segurança dos dados</h3><p>Esta versão guarda os dados no armazenamento local do navegador. Exporta regularmente os dados para CSV. Para utilização por vários treinadores e sincronização entre dispositivos será necessário ligar a aplicação a uma base de dados online.</p></div>`;$("#zoneForm").onsubmit=e=>{e.preventDefault();let v=new FormData(e.target).get("zone");if(v&&!db.zones.includes(v)){db.zones.push(v);save();render()}};$("#materialForm").onsubmit=e=>{e.preventDefault();let v=new FormData(e.target).get("material");if(v&&!db.materials.includes(v)){db.materials.push(v);save();render()}}}
function removeZone(z){if(confirm("Remover esta zona das configurações?")){db.zones=db.zones.filter(x=>x!==z);save();render()}}
function removeMaterial(z){if(confirm("Remover este material das configurações?")){db.materials=db.materials.filter(x=>x!==z);save();render()}}
function exportCSV(name,rows){if(!rows.length){toast("Não existem dados para exportar");return}let keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];let csv=[keys.join(";"),...rows.map(r=>keys.map(k=>`"${String(typeof r[k]==="object"?JSON.stringify(r[k]):r[k]??"").replace(/"/g,'""')}"`).join(";"))].join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`swim-monitor-${name}.csv`;a.click();URL.revokeObjectURL(a.href)}
window.openForm=openForm;window.edit=edit;window.remove=remove;window.toggleAthlete=toggleAthlete;window.removeZone=removeZone;window.removeMaterial=removeMaterial;
render();
